import { useEffect, useMemo, useState } from "react";
import { Archive, ArrowClockwise, ArrowUp, Brain, CaretDown, Check, CircleNotch, Code, Database, FileText, FolderOpen, Gear, Globe, HardDrives, MagnifyingGlass, Plus, ShieldCheck, SidebarSimple, Sparkle, TerminalWindow, Trash, Wrench, X } from "@phosphor-icons/react";

const i18n = {
  en:{activity:"ACTIVITY",newChat:"New conversation",recent:"RECENT PROJECTS",memory:"MEMORY",search:"Search memory",placeholder:"Ask Shamaran anything…",send:"Send",settings:"Settings",connected:"Connected",offline:"Offline",allow:"Allow changes for this message",empty:"Start a conversation",emptySub:"Ask about code, files, research, or your current project.",done:"Done",model:"Model",endpoint:"Server endpoint",steps:"Maximum steps",appearance:"Appearance",language:"Language",status:"LOCAL AGENT",general:"General",models:"Models",tools:"Tools",about:"About",workspace:"Workspace",clear:"Clear chat",source:"Model source",scan:"Scan models",scanning:"Scanning…",available:"available models",selectModel:"Choose the active model",authHint:"For a protected server, set SHAMARAN_COMPATIBLE_API_KEY in your local .env file. Secrets are never stored in this browser.",noModels:"No models found on this server."},
  fa:{activity:"فعالیت",newChat:"گفت‌وگوی تازه",recent:"پروژه‌های اخیر",memory:"حافظه",search:"جست‌وجو در حافظه",placeholder:"از شاماران هر چیزی بپرسید…",send:"ارسال",settings:"تنظیمات",connected:"متصل",offline:"قطع",allow:"اجازهٔ تغییرات برای این پیام",empty:"یک گفت‌وگو را شروع کنید",emptySub:"دربارهٔ کد، فایل‌ها، پژوهش یا پروژهٔ خود بپرسید.",done:"تمام",model:"مدل",endpoint:"نشانی سرور",steps:"حداکثر گام‌ها",appearance:"ظاهر",language:"زبان",status:"عامل محلی",general:"عمومی",models:"مدل‌ها",tools:"ابزارها",about:"درباره",workspace:"فضای کار",clear:"پاک‌کردن گفت‌وگو",source:"منبع مدل",scan:"پیداکردن مدل‌ها",scanning:"در حال جست‌وجو…",available:"مدل در دسترس",selectModel:"مدل فعال را انتخاب کنید",authHint:"برای سرور رمزدار، کلید SHAMARAN_COMPATIBLE_API_KEY را در فایل محلی .env تنظیم کنید. کلیدها در مرورگر ذخیره نمی‌شوند.",noModels:"مدلی روی این سرور پیدا نشد."},
  ku:{activity:"چالاکی",newChat:"گفتوگۆی نوێ",recent:"پڕۆژە نوێکان",memory:"بیرگە",search:"گەڕان لە بیرگە",placeholder:"هەر شتێک لە شاماران بپرسە…",send:"ناردن",settings:"ڕێکخستنەکان",connected:"پەیوەستە",offline:"پچڕاوە",allow:"ڕێگەدان بە گۆڕانکاری بۆ ئەم نامەیە",empty:"گفتوگۆیەک دەست پێ بکە",emptySub:"دەربارەی کۆد، فایل، توێژینەوە یان پڕۆژەکەت بپرسە.",done:"تەواو",model:"مۆدێل",endpoint:"ناونیشانی ڕاژەکار",steps:"زۆرترین هەنگاو",appearance:"ڕووکار",language:"زمان",status:"بریکاری ناوخۆیی",general:"گشتی",models:"مۆدێلەکان",tools:"ئامرازەکان",about:"دەربارە",workspace:"شوێنی کار",clear:"پاککردنەوەی گفتوگۆ",source:"سەرچاوەی مۆدێل",scan:"دۆزینەوەی مۆدێلەکان",scanning:"لە گەڕاندایە…",available:"مۆدێلی بەردەست",selectModel:"مۆدێلی چالاک هەڵبژێرە",authHint:"بۆ ڕاژەکاری پارێزراو، SHAMARAN_COMPATIBLE_API_KEY لە فایلی ناوخۆیی .env دابنێ. نهێنییەکان لەم وێبگەڕەدا پاشەکەوت ناکرێن.",noModels:"هیچ مۆدێلێک لەم ڕاژەکارە نەدۆزرایەوە."}
};
const starterMemory=[{id:"m1",category:"project",content:"Shamaran local agent",project:"shamaran"},{id:"m2",category:"model",content:"Qwen 3.5 via Ollama",project:null}];
const fallback=[{id:"ollama",name:"Ollama",protocol:"ollama",default_endpoint:"http://localhost:11434"}];
function Logo({small=false}){return <img className={small?"logo small":"logo"} src="/assets/shamaran-symbol.png" alt="Shamaran"/>}
function ToolIcon({name}){if(name?.includes("terminal"))return <TerminalWindow/>;if(name?.includes("git"))return <Code/>;if(name?.includes("file"))return <FileText/>;return <Wrench/>}

export function App(){
  const [status,setStatus]=useState({model:"qwen3.5:9b",models:[],max_steps:8,tools:[],ollama_ok:false,workspace:"…",providers:fallback});
  const [messages,setMessages]=useState(()=>JSON.parse(localStorage.getItem("shamaran-chat")||"[]"));
  const [memory,setMemory]=useState(starterMemory),[query,setQuery]=useState(""),[input,setInput]=useState(""),[busy,setBusy]=useState(false);
  const [settingsOpen,setSettingsOpen]=useState(true),[mobileNav,setMobileNav]=useState(false),[tab,setTab]=useState("general");
  const [model,setModel]=useState(""),[steps,setSteps]=useState(8),[allow,setAllow]=useState(false);
  const [sourceId,setSourceId]=useState(localStorage.getItem("shamaran-source")||"ollama"),[provider,setProvider]=useState("ollama"),[endpoint,setEndpoint]=useState("http://localhost:11434");
  const [availableModels,setAvailableModels]=useState([]),[discovering,setDiscovering]=useState(false),[connection,setConnection]=useState({ok:false,detail:""});
  const [lang,setLang]=useState(localStorage.getItem("shamaran-lang")||"en"),t=i18n[lang],rtl=lang!=="en";
  const sources=status.providers?.length?status.providers:fallback,activeSource=sources.find(x=>x.id===sourceId)||sources[0];
  useEffect(()=>{fetch("/api/status").then(r=>r.json()).then(data=>{setStatus(data);setSteps(data.max_steps||8);const id=localStorage.getItem("shamaran-source")||"ollama",source=data.providers?.find(x=>x.id===id)||data.providers?.[0]||fallback[0],models=source.id==="ollama"?(data.models||[]):[];setSourceId(source.id);setProvider(source.protocol);setEndpoint(localStorage.getItem(`shamaran-endpoint-${source.id}`)||source.default_endpoint);setAvailableModels(models);setModel(localStorage.getItem(`shamaran-model-${source.id}`)||data.model||models[0]||"");setConnection({ok:source.id==="ollama"&&data.ollama_ok,detail:data.ollama_detail||""})}).catch(()=>{});fetch("/api/memory").then(r=>r.json()).then(data=>data.items?.length&&setMemory(data.items)).catch(()=>{})},[]);
  useEffect(()=>localStorage.setItem("shamaran-chat",JSON.stringify(messages)),[messages]);
  useEffect(()=>{localStorage.setItem("shamaran-lang",lang);document.documentElement.lang=lang;document.documentElement.dir=rtl?"rtl":"ltr"},[lang,rtl]);
  useEffect(()=>{localStorage.setItem("shamaran-source",sourceId);localStorage.setItem(`shamaran-endpoint-${sourceId}`,endpoint);if(model)localStorage.setItem(`shamaran-model-${sourceId}`,model)},[sourceId,endpoint,model]);
  const filteredMemory=useMemo(()=>memory.filter(m=>(m.content+(m.project||"")).toLowerCase().includes(query.toLowerCase())),[memory,query]),conversations=messages.filter(m=>m.role==="user").slice(-4).reverse();
  function chooseSource(id){const source=sources.find(x=>x.id===id);if(!source)return;const models=id==="ollama"?(status.models||[]):[];setSourceId(id);setProvider(source.protocol);setEndpoint(localStorage.getItem(`shamaran-endpoint-${id}`)||source.default_endpoint);setAvailableModels(models);setModel(localStorage.getItem(`shamaran-model-${id}`)||models[0]||"");setConnection({ok:id==="ollama"&&status.ollama_ok,detail:""})}
  async function discoverModels(){setDiscovering(true);setConnection({ok:false,detail:""});try{const response=await fetch("/api/models/discover",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({provider,endpoint})}),data=await response.json();if(!response.ok)throw new Error(data.detail||"Connection failed");setAvailableModels(data.models||[]);setModel(current=>data.models?.includes(current)?current:data.models?.[0]||"");setConnection({ok:true,detail:data.models?.length?`${data.models.length} ${t.available}`:t.noModels})}catch(error){setAvailableModels([]);setConnection({ok:false,detail:error.message})}finally{setDiscovering(false)}}
  async function sendMessage(){const text=input.trim();if(!text||busy)return;if(!model){setSettingsOpen(true);setTab("models");setConnection({ok:false,detail:t.selectModel});return}setMessages(v=>[...v,{id:crypto.randomUUID(),role:"user",text}]);setInput("");setBusy(true);try{const response=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:text,provider,endpoint,model,max_steps:steps,allow_mutations:allow})}),data=await response.json();if(!response.ok)throw new Error(data.detail||"Request failed");setMessages(v=>[...v,{id:crypto.randomUUID(),role:"assistant",text:data.answer,plan:data.plan,tools:data.tools,steps:data.steps_used}])}catch(error){setMessages(v=>[...v,{id:crypto.randomUUID(),role:"error",text:error.message}])}finally{setBusy(false);setAllow(false)}}
  const newChat=()=>{setMessages([]);setMobileNav(false)};
  return <div className="app-shell" dir={rtl?"rtl":"ltr"}>
    <header className="topbar"><div className="brand"><button className="icon-button mobile-only" onClick={()=>setMobileNav(v=>!v)} aria-label="Menu"><SidebarSimple/></button><Logo small/><div><strong>SHAMARAN</strong><span>{t.status}</span></div></div><div className="status-strip"><span className="workspace-chip"><FolderOpen/> {status.workspace?.split(/[\\/]/).pop()}</span><button className={`provider-status ${connection.ok?"online":"offline"}`} onClick={()=>{setSettingsOpen(true);setTab("models")}}><i/> {activeSource?.name} · {connection.ok?t.connected:t.offline}</button><label className="compact-select"><span>{t.model}</span><select value={model} onChange={e=>setModel(e.target.value)}>{(availableModels.length?availableModels:[model].filter(Boolean)).map(x=><option key={x}>{x}</option>)}</select><CaretDown/></label><button className="icon-button" onClick={()=>setSettingsOpen(v=>!v)} aria-label={t.settings}><Gear/></button><div className="avatar">A</div></div></header>
    <aside className={`sidebar ${mobileNav?"open":""}`}><div className="sidebar-heading"><span>{t.activity}</span><button className="icon-button mobile-only" onClick={()=>setMobileNav(false)}><X/></button></div><button className="new-chat" onClick={newChat}><Plus weight="bold"/> {t.newChat}</button><section><h3>{t.recent}</h3><div className="conversation-list">{conversations.length?conversations.map((m,i)=><button key={m.id}><Archive/><span>{m.text}</span><small>{i?"Earlier":"Now"}</small></button>):<p className="muted-mini">No saved conversations yet</p>}</div></section><section className="memory-section"><h3>{t.memory}</h3><label className="search"><MagnifyingGlass/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={t.search}/></label><div className="memory-list">{filteredMemory.slice(0,5).map(item=><article key={item.id}><Brain/><div><strong>{item.project||item.category}</strong><p>{item.content}</p></div></article>)}</div></section><footer><ShieldCheck/> Local-first · Private by default</footer></aside>
    <main className="chat"><div className="chat-scroll">{!messages.length&&<div className="welcome"><div className="seal"><Logo/></div><span className="eyebrow">COPPER ARCHIVE</span><h1>{t.empty}</h1><p>{t.emptySub}</p><div className="suggestions"><button onClick={()=>setInput("Explain this project structure")}>Explore this project</button><button onClick={()=>setInput("Help me plan the next feature")}>Plan a feature</button><button onClick={()=>setInput("Check the repository status")}>Check repository</button></div></div>}{messages.map(m=><Message key={m.id} message={m}/>)}{busy&&<div className="assistant-row"><div className="assistant-mark"><Logo/></div><div className="thinking"><CircleNotch className="spin"/> Shamaran is thinking</div></div>}</div><div className="composer-wrap"><div className="composer"><textarea rows="1" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();sendMessage()}}} placeholder={t.placeholder}/><div className="composer-actions"><button className={`mutation ${allow?"active":""}`} onClick={()=>setAllow(v=>!v)}><ShieldCheck/> {t.allow}</button><button className="send" disabled={!input.trim()||busy} onClick={sendMessage}><ArrowUp weight="bold"/><span>{t.send}</span></button></div></div><p className="disclaimer">Shamaran works locally. Review tool actions before allowing changes.</p></div></main>
    <aside className={`settings ${settingsOpen?"open":""}`}><div className="settings-title"><div><span className="eyebrow">CONTROL ROOM</span><h2>{t.settings}</h2></div><button className="icon-button" onClick={()=>setSettingsOpen(false)}><X/></button></div><nav>{[["general",Gear],["models",HardDrives],["tools",Wrench],["about",Sparkle]].map(([key,Icon])=><button className={tab===key?"active":""} key={key} onClick={()=>setTab(key)}><Icon/>{t[key]}</button>)}</nav>
      {tab==="general"&&<div className="settings-body"><Setting icon={<Globe/>} title={t.language}><div className="segmented">{[["en","English"],["fa","فارسی"],["ku","سۆرانی"]].map(([key,label])=><button className={lang===key?"active":""} onClick={()=>setLang(key)} key={key}>{label}</button>)}</div></Setting><Setting icon={<FolderOpen/>} title={t.workspace}><div className="path-box">{status.workspace}</div></Setting><Setting icon={<Archive/>} title={t.appearance}><div className="theme-preview"><span/><div><strong>Copper Archive</strong><small>Warm ivory & aubergine</small></div><Check/></div></Setting></div>}
      {tab==="models"&&<div className="settings-body model-hub"><Setting icon={<HardDrives/>} title={t.source}><div className="provider-grid">{sources.map(source=><button key={source.id} className={`provider-card ${sourceId===source.id?"active":""}`} onClick={()=>chooseSource(source.id)}><span>{source.name}</span><small>{source.protocol==="ollama"?"Native":"Compatible API"}</small>{sourceId===source.id&&<Check/>}</button>)}</div></Setting><Setting icon={<Database/>} title={t.endpoint}><div className="connect-row"><input className="field" value={endpoint} onChange={e=>{setEndpoint(e.target.value);setConnection({ok:false,detail:""})}} spellCheck="false"/><button className="scan-button" onClick={discoverModels} disabled={discovering||!endpoint.trim()}>{discovering?<CircleNotch className="spin"/>:<ArrowClockwise/>}{discovering?t.scanning:t.scan}</button></div>{connection.detail&&<p className={`connection-note ${connection.ok?"success":"failure"}`}>{connection.ok?<Check/>:<X/>}{connection.detail}</p>}</Setting><Setting icon={<Sparkle/>} title={t.selectModel}><select className="field" value={model} onChange={e=>setModel(e.target.value)} disabled={!availableModels.length}><option value="">{availableModels.length?t.selectModel:t.noModels}</option>{availableModels.map(x=><option key={x}>{x}</option>)}</select>{availableModels.length>0&&<span className="model-count">{availableModels.length} {t.available}</span>}</Setting>{provider==="openai-compatible"&&<p className="auth-note"><ShieldCheck/>{t.authHint}</p>}<Setting icon={<Sparkle/>} title={t.steps}><div className="range-line"><input type="range" min="1" max="32" value={steps} onChange={e=>setSteps(Number(e.target.value))}/><b>{steps}</b></div></Setting></div>}
      {tab==="tools"&&<div className="settings-body tool-list">{status.tools?.map(tool=><article key={tool.name}><ToolIcon name={tool.name}/><div><strong>{tool.name}</strong><p>{tool.description}</p></div><span className={`safety ${tool.safety_level}`}>{tool.safety_level}</span></article>)}</div>}
      {tab==="about"&&<div className="settings-body about"><Logo/><h3>Shamaran {status.version}</h3><p>A secure, local-first agent created by Ashkan Allahveisi.</p><div className="about-stat"><span>Provider</span><b>{activeSource?.name}</b></div><div className="about-stat"><span>Memory</span><b>{status.memory_ok?"Ready":"Unavailable"}</b></div></div>}
      <div className="settings-footer"><button onClick={()=>setSettingsOpen(false)}>{t.done}</button><button className="clear-button" onClick={newChat}><Trash/> {t.clear}</button></div></aside>
  </div>
}
function Setting({icon,title,children}){return <section className="setting-group"><h3>{icon}{title}</h3>{children}</section>}
function Message({message}){if(message.role==="user")return <div className="user-row"><div className="user-bubble">{message.text}</div><div className="avatar">A</div></div>;return <div className={`assistant-row ${message.role==="error"?"error":""}`}><div className="assistant-mark"><Logo/></div><div className="response"><div className="response-meta"><strong>{message.role==="error"?"Connection error":"Shamaran"}</strong>{message.steps&&<span>{message.steps} steps</span>}</div>{message.plan?.length>0&&<div className="plan-card"><div className="card-title"><Sparkle/> Plan</div>{message.plan.map((step,i)=><p key={i}><span>{String(i+1).padStart(2,"0")}</span>{step}</p>)}</div>}{message.tools?.map((tool,i)=><div className="tool-event" key={i}><ToolIcon name={tool.name}/><div><strong>{tool.name}</strong><p>{tool.summary}</p></div><span className={tool.ok?"tool-ok":"tool-fail"}>{tool.ok?<Check/>:<X/>}</span></div>)}<div className="answer">{message.text}</div></div></div>}
