import { useEffect, useMemo, useState } from "react";
import {
  Archive, ArrowUp, Brain, CaretDown, Check, CircleNotch, Code,
  Database, FileText, FolderOpen, Gear, Globe, HardDrives, MagnifyingGlass,
  Plus, ShieldCheck, SidebarSimple, Sparkle, TerminalWindow, Trash, Wrench, X,
} from "@phosphor-icons/react";

const i18n = {
  en: { activity: "ACTIVITY", newChat: "New conversation", recent: "RECENT PROJECTS", memory: "MEMORY", search: "Search memory", placeholder: "Ask Shamaran anything…", send: "Send", settings: "Settings", connected: "Connected", allow: "Allow changes for this message", empty: "Start a conversation", emptySub: "Ask about code, files, research, or your current project.", done: "Done", model: "Model", endpoint: "Ollama endpoint", steps: "Maximum steps", appearance: "Appearance", language: "Language", status: "LOCAL AGENT", general: "General", models: "Models", tools: "Tools", about: "About", workspace: "Workspace", clear: "Clear chat" },
  fa: { activity: "فعالیت", newChat: "گفت‌وگوی تازه", recent: "پروژه‌های اخیر", memory: "حافظه", search: "جست‌وجو در حافظه", placeholder: "از شاماران هر چیزی بپرسید…", send: "ارسال", settings: "تنظیمات", connected: "متصل", allow: "اجازهٔ تغییرات برای این پیام", empty: "یک گفت‌وگو را شروع کنید", emptySub: "دربارهٔ کد، فایل‌ها، پژوهش یا پروژهٔ خود بپرسید.", done: "تمام", model: "مدل", endpoint: "نشانی Ollama", steps: "حداکثر گام‌ها", appearance: "ظاهر", language: "زبان", status: "عامل محلی", general: "عمومی", models: "مدل‌ها", tools: "ابزارها", about: "درباره", workspace: "فضای کار", clear: "پاک‌کردن گفت‌وگو" },
  ku: { activity: "چالاکی", newChat: "گفتوگۆی نوێ", recent: "پڕۆژە نوێکان", memory: "بیرگە", search: "گەڕان لە بیرگە", placeholder: "هەر شتێک لە شاماران بپرسە…", send: "ناردن", settings: "ڕێکخستنەکان", connected: "پەیوەستە", allow: "ڕێگەدان بە گۆڕانکاری بۆ ئەم نامەیە", empty: "گفتوگۆیەک دەست پێ بکە", emptySub: "دەربارەی کۆد، فایل، توێژینەوە یان پڕۆژەکەت بپرسە.", done: "تەواو", model: "مۆدێل", endpoint: "ناونیشانی Ollama", steps: "زۆرترین هەنگاو", appearance: "ڕووکار", language: "زمان", status: "بریکاری ناوخۆیی", general: "گشتی", models: "مۆدێلەکان", tools: "ئامرازەکان", about: "دەربارە", workspace: "شوێنی کار", clear: "پاککردنەوەی گفتوگۆ" },
};
const starterMemory = [{ id: "m1", category: "project", content: "Shamaran local agent", project: "shamaran" }, { id: "m2", category: "model", content: "Qwen 3.5 via Ollama", project: null }];
function Logo({ small = false }) { return <img className={small ? "logo small" : "logo"} src="/assets/shamaran-symbol.png" alt="Shamaran" />; }
function ToolIcon({ name }) { if (name?.includes("terminal")) return <TerminalWindow />; if (name?.includes("git")) return <Code />; if (name?.includes("file")) return <FileText />; return <Wrench />; }

export function App() {
  const [status, setStatus] = useState({ model: "qwen3.5:9b", models: [], max_steps: 8, tools: [], ollama_ok: false, workspace: "…" });
  const [messages, setMessages] = useState(() => JSON.parse(localStorage.getItem("shamaran-chat") || "[]"));
  const [memory, setMemory] = useState(starterMemory);
  const [query, setQuery] = useState(""); const [input, setInput] = useState(""); const [busy, setBusy] = useState(false);
  const [settingsOpen, setSettingsOpen] = useState(true); const [mobileNav, setMobileNav] = useState(false); const [tab, setTab] = useState("general");
  const [model, setModel] = useState(""); const [steps, setSteps] = useState(8); const [allow, setAllow] = useState(false);
  const [lang, setLang] = useState(localStorage.getItem("shamaran-lang") || "en"); const t = i18n[lang]; const rtl = lang !== "en";
  useEffect(() => { fetch("/api/status").then(r => r.json()).then(data => { setStatus(data); setModel(data.model || data.models?.[0] || ""); setSteps(data.max_steps || 8); }).catch(() => {}); fetch("/api/memory").then(r => r.json()).then(data => data.items?.length && setMemory(data.items)).catch(() => {}); }, []);
  useEffect(() => localStorage.setItem("shamaran-chat", JSON.stringify(messages)), [messages]);
  useEffect(() => { localStorage.setItem("shamaran-lang", lang); document.documentElement.lang = lang; document.documentElement.dir = rtl ? "rtl" : "ltr"; }, [lang, rtl]);
  const filteredMemory = useMemo(() => memory.filter(m => (m.content + (m.project || "")).toLowerCase().includes(query.toLowerCase())), [memory, query]);
  const conversations = messages.filter(m => m.role === "user").slice(-4).reverse();
  async function sendMessage() { const text = input.trim(); if (!text || busy) return; setMessages(v => [...v, { id: crypto.randomUUID(), role: "user", text }]); setInput(""); setBusy(true); try { const response = await fetch("/api/chat", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ message: text, model, max_steps: steps, allow_mutations: allow }) }); const data = await response.json(); if (!response.ok) throw new Error(data.detail || "Request failed"); setMessages(v => [...v, { id: crypto.randomUUID(), role: "assistant", text: data.answer, plan: data.plan, tools: data.tools, steps: data.steps_used }]); } catch (error) { setMessages(v => [...v, { id: crypto.randomUUID(), role: "error", text: error.message }]); } finally { setBusy(false); setAllow(false); } }
  const newChat = () => { setMessages([]); setMobileNav(false); };
  return <div className="app-shell" dir={rtl ? "rtl" : "ltr"}>
    <header className="topbar"><div className="brand"><button className="icon-button mobile-only" onClick={() => setMobileNav(v => !v)} aria-label="Menu"><SidebarSimple /></button><Logo small /><div><strong>SHAMARAN</strong><span>{t.status}</span></div></div><div className="status-strip"><span className="workspace-chip"><FolderOpen /> {status.workspace?.split(/[\\/]/).pop()}</span><span className={status.ollama_ok ? "online" : "offline"}><i /> Ollama · {status.ollama_ok ? t.connected : "Offline"}</span><label className="compact-select"><span>{t.model}</span><select value={model} onChange={e => setModel(e.target.value)}>{(status.models?.length ? status.models : [model || "qwen3.5:9b"]).map(x => <option key={x}>{x}</option>)}</select><CaretDown /></label><button className="icon-button" onClick={() => setSettingsOpen(v => !v)} aria-label={t.settings}><Gear /></button><div className="avatar">A</div></div></header>
    <aside className={`sidebar ${mobileNav ? "open" : ""}`}><div className="sidebar-heading"><span>{t.activity}</span><button className="icon-button mobile-only" onClick={() => setMobileNav(false)}><X /></button></div><button className="new-chat" onClick={newChat}><Plus weight="bold" /> {t.newChat}</button><section><h3>{t.recent}</h3><div className="conversation-list">{conversations.length ? conversations.map((m, i) => <button key={m.id}><Archive /><span>{m.text}</span><small>{i ? "Earlier" : "Now"}</small></button>) : <p className="muted-mini">No saved conversations yet</p>}</div></section><section className="memory-section"><h3>{t.memory}</h3><label className="search"><MagnifyingGlass /><input value={query} onChange={e => setQuery(e.target.value)} placeholder={t.search} /></label><div className="memory-list">{filteredMemory.slice(0, 5).map(item => <article key={item.id}><Brain /><div><strong>{item.project || item.category}</strong><p>{item.content}</p></div></article>)}</div></section><footer><ShieldCheck /> Local-first · Private by default</footer></aside>
    <main className="chat"><div className="chat-scroll">{!messages.length && <div className="welcome"><div className="seal"><Logo /></div><span className="eyebrow">COPPER ARCHIVE</span><h1>{t.empty}</h1><p>{t.emptySub}</p><div className="suggestions"><button onClick={() => setInput("Explain this project structure")}>Explore this project</button><button onClick={() => setInput("Help me plan the next feature")}>Plan a feature</button><button onClick={() => setInput("Check the repository status")}>Check repository</button></div></div>}{messages.map(message => <Message key={message.id} message={message} />)}{busy && <div className="assistant-row"><div className="assistant-mark"><Logo /></div><div className="thinking"><CircleNotch className="spin" /> Shamaran is thinking</div></div>}</div><div className="composer-wrap"><div className="composer"><textarea rows="1" value={input} onChange={e => setInput(e.target.value)} onKeyDown={e => { if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); sendMessage(); } }} placeholder={t.placeholder} /><div className="composer-actions"><button className={`mutation ${allow ? "active" : ""}`} onClick={() => setAllow(v => !v)}><ShieldCheck /> {t.allow}</button><button className="send" disabled={!input.trim() || busy} onClick={sendMessage}><ArrowUp weight="bold" /><span>{t.send}</span></button></div></div><p className="disclaimer">Shamaran works locally. Review tool actions before allowing changes.</p></div></main>
    <aside className={`settings ${settingsOpen ? "open" : ""}`}><div className="settings-title"><div><span className="eyebrow">CONTROL ROOM</span><h2>{t.settings}</h2></div><button className="icon-button" onClick={() => setSettingsOpen(false)}><X /></button></div><nav>{[["general", Gear], ["models", HardDrives], ["tools", Wrench], ["about", Sparkle]].map(([key, Icon]) => <button className={tab === key ? "active" : ""} key={key} onClick={() => setTab(key)}><Icon />{t[key]}</button>)}</nav>{tab === "general" && <div className="settings-body"><SettingLabel icon={<Globe />} title={t.language}><div className="segmented">{[["en", "English"], ["fa", "فارسی"], ["ku", "سۆرانی"]].map(([key, label]) => <button className={lang === key ? "active" : ""} onClick={() => setLang(key)} key={key}>{label}</button>)}</div></SettingLabel><SettingLabel icon={<FolderOpen />} title={t.workspace}><div className="path-box">{status.workspace}</div></SettingLabel><SettingLabel icon={<Archive />} title={t.appearance}><div className="theme-preview"><span /><div><strong>Copper Archive</strong><small>Warm ivory & aubergine</small></div><Check /></div></SettingLabel></div>}{tab === "models" && <div className="settings-body"><SettingLabel icon={<HardDrives />} title={t.model}><select className="field" value={model} onChange={e => setModel(e.target.value)}>{(status.models?.length ? status.models : [model || "qwen3.5:9b"]).map(x => <option key={x}>{x}</option>)}</select></SettingLabel><SettingLabel icon={<Database />} title={t.endpoint}><input className="field" readOnly value={status.endpoint || "http://localhost:11434"} /></SettingLabel><SettingLabel icon={<Sparkle />} title={t.steps}><div className="range-line"><input type="range" min="1" max="32" value={steps} onChange={e => setSteps(Number(e.target.value))} /><b>{steps}</b></div></SettingLabel></div>}{tab === "tools" && <div className="settings-body tool-list">{status.tools?.map(tool => <article key={tool.name}><ToolIcon name={tool.name} /><div><strong>{tool.name}</strong><p>{tool.description}</p></div><span className={`safety ${tool.safety_level}`}>{tool.safety_level}</span></article>)}</div>}{tab === "about" && <div className="settings-body about"><Logo /><h3>Shamaran {status.version}</h3><p>A secure, local-first agent created by Ashkan Allahveisi.</p><div className="about-stat"><span>Provider</span><b>{status.provider}</b></div><div className="about-stat"><span>Memory</span><b>{status.memory_ok ? "Ready" : "Unavailable"}</b></div></div>}<div className="settings-footer"><button onClick={() => setSettingsOpen(false)}>{t.done}</button><button className="clear-button" onClick={newChat}><Trash /> {t.clear}</button></div></aside>
  </div>;
}
function SettingLabel({ icon, title, children }) { return <section className="setting-group"><h3>{icon}{title}</h3>{children}</section>; }
function Message({ message }) { if (message.role === "user") return <div className="user-row"><div className="user-bubble">{message.text}</div><div className="avatar">A</div></div>; return <div className={`assistant-row ${message.role === "error" ? "error" : ""}`}><div className="assistant-mark"><Logo /></div><div className="response"><div className="response-meta"><strong>{message.role === "error" ? "Connection error" : "Shamaran"}</strong>{message.steps && <span>{message.steps} steps</span>}</div>{message.plan?.length > 0 && <div className="plan-card"><div className="card-title"><Sparkle /> Plan</div>{message.plan.map((step, i) => <p key={i}><span>{String(i + 1).padStart(2, "0")}</span>{step}</p>)}</div>}{message.tools?.map((tool, i) => <div className="tool-event" key={i}><ToolIcon name={tool.name} /><div><strong>{tool.name}</strong><p>{tool.summary}</p></div><span className={tool.ok ? "tool-ok" : "tool-fail"}>{tool.ok ? <Check /> : <X />}</span></div>)}<div className="answer">{message.text}</div></div></div>; }
